# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default:
            connections:
                - url: '%env(resolve:INDEX)%'
    indexes:
        app:
            index_name: app_%kernel.environment%
            settings:
                index:
                    analysis:
                        filter:
                            autocomplete_filter:
                                type: "edge_ngram"
                                min_gram: 2
                                max_gram: 20
                        analyzer:
                            autocomplete:
                                type: custom
                                tokenizer: standard
                                filter: [ "lowercase", "autocomplete_filter"]
                                language: English
                            snowball_analyzer:
                                type: snowball
                                language: English 
            types:
                event:
                    properties:
                        id: { type: keyword }
                        Date: { type: date }
                        Apm: { type: keyword }
                        Series: 
                            type: "nested"
                            properties:
                                id: { type: text }
                                Name: { type: text }
                                Complete: { type: boolean }
                        Reading: { analyzer: snowball_analyzer }
                        SecondReading: ~
                        Title: { analyzer: snowball_analyzer }
                        Speaker: 
                            type: "nested"
                            properties:
                                id: { type: text }
                                Name: { type: text }
                                Organisation: { type: text }
                                Website: ~
                        attachmentMetadata: 
                            type: "nested"
                            properties: 
                                id: { type: text }
                                mimeType: { type: text }
                                contentLength: { type: text }
                                fileLocation: { type: text }
                                complete: ~
                                hash: { type: text }
                                isPublic: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Event
                        provider: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                        provider:
                            batch_size: 100
