# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    view:
        formats:
            json: true
            html: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: json
        view_response_listener:  true
    disable_csrf_role: ROLE_API
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', fallback_format: html, prefer_extension: true }

