twig:
    globals:
        creche: '%env(CRECHE)%'
        church_cleaning: '%env(CHURCHCLEANING)%'
        morning_setup: '%env(MORNINGSETUP)%'
        sunday_school: '%env(SUNDAYSCHOOL)%'
        tea_and_coffee: '%env(TEAANDCOFFEE)%'