#index:
#    path: /
#    controller: App\Controller\DefaultController::index

security_logout:
    path: /logout
    methods: GET

wecmk_public_home:
    path: /
    host: "www.wecmk.org"
    schemes: "https"
    defaults: 
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
